version: "3.9"

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ./Senior_Developer_Assessment:/app        # mount source code for live edits
      - /app/bin                                  # exclude bin
      - /app/obj                                  # exclude obj
      - ./logs:/app/logs                          # persist logs
    ports:
      - "5000:80"    # API accessible at localhost:5000
      - "5001:443"   # optional HTTPS for dev

  db:
    ports:
      - "1433:1433"  # expose SQL for local management tools
