version: "3.9"

services:
  api:
    build:
      context: ./Senior_Developer_Assessment
      dockerfile: Dockerfile
    environment:
      - DEFAULT_CONNECTION=Server=db;Database=AssessmentDb;User Id=sa;Password=YourStrong!Passw0rd;
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
